use_frameworks!

platform :ios, '8.0'

target 'CJMAlertViewController_Example' do
  pod 'CJMAlertViewController', :path => '../'

  target 'CJMAlertViewController_Tests' do
    inherit! :search_paths

    
  end
end
